site_name: Documentation du projet
site_url: https://Les-Baroudeurs-du-Bit.github.io/mkdocs/

theme:
  name: material
  language: fr
  palette:
    primary: custom
    accent: custom
  font:
    text: Arial
    code: Roboto Mono

extra_css:
  - Stylesheets/extra.css

nav:
  - Accueil: index.md
  - "Déroulement du projet": deroulement.md
  - Comparaison: tab-comparatifs.md
  - "Analyse Stack": comp-stack.md
  - "Suivi des tokens": tab-tokens.md
